<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="Read_Strain" Id="{16e1bd7e-c7ed-4e20-b439-b4719d1dd6a8}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Read_Strain
VAR
	Strain_Left		: REAL := 0;
	Strain_Right	: REAL := 0;
	
	//nBit_Left AT %I*	: INT;
	//nBit_Right AT %I*	: INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[;]]></ST>
    </Implementation>
    <LineIds Name="Read_Strain">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>