<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="Save_IMU" Id="{0593a3af-b256-48a9-a4b4-c7aba26ff107}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Save_IMU
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Save_IMU">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>